name: ssdv-fec

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  default_features:
    name: Default features
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssdv-fec
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings      
    - name: Doc
      run: RUSTFLAGS="-D warnings" cargo doc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  no_features:
    name: No features
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssdv-fec
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --no-default-features -- -D warnings
    - name: Doc
      run: RUSTFLAGS="-D warnings" cargo doc --no-default-features
    - name: Build
      run: cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --no-default-features --verbose
